version: 0.0
os: linux
files:
  - source: gooru-web
    destination: /tmp/gooru-web
hooks:
  ApplicationStop:
    - location: ./.deploy/nginx-stop.sh
      timeout: 120
      runas: ubuntu
  BeforeInstall:
    - location: ./.deploy/remove-app.sh
      timeout: 120
      runas: ubuntu
  AfterInstall:
    - location: ./.deploy/add-app.sh
      timeout: 120
      runas: ubuntu
  ApplicationStart:
    - location: ./.deploy/nginx-start.sh
      timeout: 120
      runas: ubuntu
